name: Build STL
on: [push, workflow_dispatch]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Build STL
        uses: Carlmut-Industries/openscad-docker-action@debug
        with:
          root_file: adapter-22mm.scad
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "/tmp/output.stl,/tmp/render.png"
          token: ${{ secrets.GITHUB_TOKEN }}
