name: Build STL
on: [push, workflow_dispatch]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Build STL
        uses: Carlmut-Industries/openscad-docker-action@main
        with:
          root_file: adapter-22mm.scad
